const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.video,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.Tween,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.PlayAtPosition,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{monster: 0},
	{BG: 0},
	{road: 0},
	{Player: 0},
	{Touch: 0},
	{Hurdle_B1: 0},
	{Hurdle_R1: 0},
	{子彈: 0},
	{bullet: 0},
	{補間動畫: 0},
	{gameover: 0},
	{背景: 0},
	{StartInterface: 0},
	{按鈕: 0},
	{RecruitmentInformation: 0},
	{Hurdle_R2: 0},
	{Hurdle_B2: 0},
	{monster2: 0},
	{BGM: 0},
	{beaten: 0},
	{BulletAngle: 0},
	{direction: 0},
	{Monster: 0},
	{放大值: 0}
];

self.InstanceType = {
	monster: class extends self.ISpriteInstance {},
	BG: class extends self.IWorldInstance {},
	road: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Hurdle_B1: class extends self.ISpriteInstance {},
	Hurdle_R1: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	背景: class extends self.IWorldInstance {},
	StartInterface: class extends self.ISpriteInstance {},
	按鈕: class extends self.IButtonInstance {},
	RecruitmentInformation: class extends self.ISpriteInstance {},
	Hurdle_R2: class extends self.ISpriteInstance {},
	Hurdle_B2: class extends self.ISpriteInstance {},
	monster2: class extends self.ISpriteInstance {},
	BGM: class extends self.IInstance {}
}